START .\LaunchServer.bat
START .\LaunchServer.bat
START .\LaunchServer.bat
START .\LaunchServer.bat
START .\LaunchServer.bat
START .\LaunchServer.bat
START .\LaunchServer.bat
START .\LaunchServer.bat
START .\LaunchServer.bat