---
ci_version: &ci_version "1.1"

steps:
  # New build pipeline
  # Trigger a 4.26 build
  - trigger: "unrealgdkbuild-ci"
    label: "exampleproject-ci"
    async: false
    build:
      branch: *ci_version
      message: "exampleproject-4.26 ${BUILDKITE_MESSAGE}"
      env: 
        BUILD_TYPE: "EXAMPLE"
        GDK_BRANCH: "${GDK_BRANCH:-0.13.0}" # NOTE: temp fix for new ci release interop issues
        ENGINE_BRANCH: "${ENGINE_BRANCH:-4.26-SpatialOSUnrealGDK-0.13.0}" # NOTE: temp fix for new ci release interop issues
        ENGINE_MAJOR: "4.26"
        PROJECT_BRANCH: "${BUILDKITE_BRANCH}"
        USE_FASTBUILD: "True"
        IS_BUILDKITE_BUILD: "True"
        BUILD_ANDROID: "True"
        SKIP_TESTS: "True"
        CLEAN_BUILD: "False"
        START_DEPLOYMENT: "True"
        SPATIAL_PROJECT_NAME: "unreal_gdk"
# TODO: bring back deployment link notifies UNR-5391
