---
ci_version: &ci_version "1.1"

steps:
  # New build pipeline
  # Trigger a 4.26 build
  - trigger: "unrealgdkbuild-ci"
    label: "exampleproject-ci"
    async: false
    build:
      branch: *ci_version
      message: "exampleproject-4.26 ${BUILDKITE_MESSAGE}"
      env: 
        BUILD_TYPE: "EXAMPLE"
        GDK_BRANCH: "master"
        ENGINE_BRANCH: "4.26-SpatialOSUnrealGDK"
        ENGINE_MAJOR: "4.26"
        PROJECT_BRANCH: "${BUILDKITE_BRANCH}"
        USE_FASTBUILD: "True"
        IS_BUILDKITE_BUILD: "True"
        BUILD_ANDROID: "True"
        SKIP_TESTS: "True"
        CLEAN_BUILD: "False"
        START_DEPLOYMENT: "True"
        SPATIAL_PROJECT_NAME: "unreal_gdk"
        BUILD_LINUX_SERVER_WORKER: "True"
        BUILD_WINDOWS_CLIENT_WORKER: "True"
        BUILD_SIM_PLAYER_WORKER: "False"
# TODO: bring back deployment link notifies UNR-5391
