script_runner: &script_runner
  agents:
  - "agent_count=8"
  - "capable_of_building=platform"
  - "environment=production"
  - "machine_type=quarter"
  - "permission_set=builder"
  - "platform=linux"
  - "queue=${CI_LINUX_BUILDER_QUEUE:-v4-2019-12-12-bk5225-daecba805768d787}"
  - "scaler_version=2"
  - "working_hours_time_zone=london"

common: &common
  agents:
    - "agent_count=1"
    - "capable_of_building=gdk-for-unreal"
    - "environment=production"
    - "machine_type=quad"
    - "permission_set=builder"
    - "platform=windows"
    - "scaler_version=2"
    - "queue=${CI_WINDOWS_BUILDER_QUEUE:-v4-2020-02-14-bk8202-b661030c18138bee}"
  timeout_in_minutes: 60 # TODO(ENG-548): reduce timeout once agent-cold-start is optimised.
  retry:
    automatic:
        # This is designed to trap and retry failures because agent lost connection. Agent exits with -1 in this case.
      - exit_status: -1
        limit: 3
  plugins:
    - ca-johnson/taskkill#v4.1: ~

# NOTE: step labels turn into commit-status names like {org}/{repo}/{pipeline}/{step-label}, lower-case and hyphenated.
# These are then relied on to have stable names by other things, so once named, please beware renaming has consequences.

steps:
  - label: "generate-pipeline-steps"
    commands: 
      - "chmod -R +rwx ci"
      - "ci/generate-pipeline-steps.sh"
    env:
      ENGINE_VERSION: "${ENGINE_VERSION}"
    <<: *script_runner

  - wait

  - label: "slack-notify"
    if: build.env("SLACK_NOTIFY") == "true" || build.branch == "master"
    command: "powershell -NoProfile -NonInteractive -InputFormat Text -Command ./ci/slack-notify.ps1"
    <<: *common # This folds the YAML named anchor into this step. Overrides, if any, should follow, not precede.
