---
ci_version: &ci_version "1.2"

steps:
  # New build pipeline
  # Trigger a 4.26 build
  - trigger: "unrealgdkbuild-ci"
    label: "exampleproject-ci"
    async: false
    build:
      branch: *ci_version
      message: "exampleproject-4.26 ${BUILDKITE_MESSAGE}"
      env: 
        BUILD_TYPE: "EXAMPLE"
        GDK_BRANCH: ""${GDK_BRANCH:-match_branch_name_pref::0.13.1-rc}"
        ENGINE_BRANCH: "${ENGINE_BRANCH_426:-match_branch_name_pref_engine::4.26-SpatialOSUnrealGDK-0.13.1-rc}"
        ENGINE_MAJOR: "4.26"
        PROJECT_BRANCH: "main_branch::${BUILDKITE_BRANCH}"
        USE_FASTBUILD: "True"
        IS_BUILDKITE_BUILD: "True"
        BUILD_ANDROID: "True"
        SKIP_TESTS: "True"
        CLEAN_BUILD: "False"
        START_DEPLOYMENT: "True"
        SPATIAL_PROJECT_NAME: "unreal_gdk"
# TODO: bring back deployment link notifies UNR-5391
