common: &common
  agents:
    - "capable_of_building=gdk-for-unreal"
    - "environment=production"
    - "permission_set=builder"
    - "platform=windows"
    - "queue=${CI_WINDOWS_BUILDER_QUEUE:-v3-1569490589-f9345a43b21a6cec-------z}"
  timeout_in_minutes: 60 # TODO(ENG-548): reduce timeout once agent-cold-start is optimised.
  retry:
    automatic:
        # This is designed to trap and retry failures because agent lost connection. Agent exits with -1 in this case.
      - exit_status: -1
        limit: 3
  plugins:
    - ca-johnson/taskkill#v4.1: ~

steps:
  - label: "build-and-deploy-:windows:"
    command: powershell -NoProfile -NonInteractive -InputFormat Text -Command ./ci/setup-and-build.ps1
    <<: *common # This folds the YAML named anchor into this step. Overrides, if any, should follow, not precede.
    artifact_paths:
      - "UnrealEngine/Engine/Programs/AutomationTool/Saved/Logs/*"
