// Generated by Unreal External Schema Codegen

#pragma once

#include "CoreMinimal.h"
#include "Utils/SchemaOption.h"
#include <WorkerSDK/improbable/c_schema.h>
#include <WorkerSDK/improbable/c_worker.h>

#include "../../ExternalSchemaHelperFunctions.h"

namespace improbable {
namespace postgres {

// Generated from C:\DEV\UnrealGDKExampleProject\Game\Plugins\UnrealGDK\SpatialGDK\Build\Scripts\dbsync\postgres.schema(13,1)
class FieldTypeAttribute : public improbable::SpatialType
{
public:
	// Creates a new instance with specified arguments for each field.
	FieldTypeAttribute(const FString& Type);
	// Creates a new instance with default values for each field.
	FieldTypeAttribute();
	// Creates a new instance with default values for each field. This is
	// equivalent to a default-constructed instance.
	static FieldTypeAttribute Create() { return {}; }
	// Copyable and movable.
	FieldTypeAttribute(FieldTypeAttribute&&) = default;
	FieldTypeAttribute(const FieldTypeAttribute&) = default;
	FieldTypeAttribute& operator=(FieldTypeAttribute&&) = default;
	FieldTypeAttribute& operator=(const FieldTypeAttribute&) = default;
	~FieldTypeAttribute() = default;
	
	bool operator==(const FieldTypeAttribute&) const;
	bool operator!=(const FieldTypeAttribute&) const;
	
	// Serialize this object data into the C API argument
	void Serialize(Schema_Object* SchemaObject) const override;
	
	// Deserialize the C API object argument into an instance of this class and return it
	static FieldTypeAttribute Deserialize(Schema_Object* SchemaObject);
	
	// Field Type = 1
	const FString& GetType() const;
	FString& GetType();
	FieldTypeAttribute& SetType(const FString&);
	
private:
	FString _Type;
};

inline uint32 GetTypeHash(const FieldTypeAttribute& Value);

} // namespace postgres
} // namespace improbable

