// Generated by Unreal External Schema Codegen

#include "PrimaryKeyAttribute.h"
#include <set>
#include "../../MapEquals.h"

// Generated from C:\DEV\UnrealGDKExampleProject\Game\Plugins\UnrealGDK\SpatialGDK\Build\Scripts\dbsync\postgres.schema(7,1)
namespace improbable {
namespace postgres {

PrimaryKeyAttribute::PrimaryKeyAttribute() {}

bool PrimaryKeyAttribute::operator==(const PrimaryKeyAttribute& Value) const
{
	return true;
}

bool PrimaryKeyAttribute::operator!=(const PrimaryKeyAttribute& Value) const
{
	return !operator== (Value);
}

void PrimaryKeyAttribute::Serialize(Schema_Object* SchemaObject) const {}

PrimaryKeyAttribute PrimaryKeyAttribute::Deserialize(Schema_Object* SchemaObject)
{
	return PrimaryKeyAttribute::Create();
}

uint32 GetTypeHash(const improbable::postgres::PrimaryKeyAttribute& Value)
{
	uint32 Result = 1327;
	
	return Result;
}

} // namespace postgres
} // namespace improbable
