// Generated by Unreal External Schema Codegen

#pragma once

#include "CoreMinimal.h"
#include "Utils/SchemaOption.h"
#include <WorkerSDK/improbable/c_schema.h>
#include <WorkerSDK/improbable/c_worker.h>

#include "../../ExternalSchemaHelperFunctions.h"

namespace improbable {
namespace database_sync {

// Generated from C:\DEV\UnrealGDKExampleProject\Game\Plugins\UnrealGDK\SpatialGDK\Build\Scripts\dbsync\database_sync.schema(223,1)
class AssociatePathWithClientResponse : public improbable::SpatialType
{
public:
	// Creates a new instance with default values for each field.
	AssociatePathWithClientResponse();
	// Creates a new instance with default values for each field. This is
	// equivalent to a default-constructed instance.
	static AssociatePathWithClientResponse Create() { return {}; }
	// Copyable and movable.
	AssociatePathWithClientResponse(AssociatePathWithClientResponse&&) = default;
	AssociatePathWithClientResponse(const AssociatePathWithClientResponse&) = default;
	AssociatePathWithClientResponse& operator=(AssociatePathWithClientResponse&&) = default;
	AssociatePathWithClientResponse& operator=(const AssociatePathWithClientResponse&) = default;
	~AssociatePathWithClientResponse() = default;
	
	bool operator==(const AssociatePathWithClientResponse&) const;
	bool operator!=(const AssociatePathWithClientResponse&) const;
	
	// Serialize this object data into the C API argument
	void Serialize(Schema_Object* SchemaObject) const override;
	
	// Deserialize the C API object argument into an instance of this class and return it
	static AssociatePathWithClientResponse Deserialize(Schema_Object* SchemaObject);
	
};

inline uint32 GetTypeHash(const AssociatePathWithClientResponse& Value);

} // namespace database_sync
} // namespace improbable

