// Generated by Unreal External Schema Codegen

#include "AssociatePathWithClientResponse.h"
#include <set>
#include "../../MapEquals.h"

// Generated from C:\DEV\UnrealGDKExampleProject\Game\Plugins\UnrealGDK\SpatialGDK\Build\Scripts\dbsync\database_sync.schema(223,1)
namespace improbable {
namespace database_sync {

AssociatePathWithClientResponse::AssociatePathWithClientResponse() {}

bool AssociatePathWithClientResponse::operator==(const AssociatePathWithClientResponse& Value) const
{
	return true;
}

bool AssociatePathWithClientResponse::operator!=(const AssociatePathWithClientResponse& Value) const
{
	return !operator== (Value);
}

void AssociatePathWithClientResponse::Serialize(Schema_Object* SchemaObject) const {}

AssociatePathWithClientResponse AssociatePathWithClientResponse::Deserialize(Schema_Object* SchemaObject)
{
	return AssociatePathWithClientResponse::Create();
}

uint32 GetTypeHash(const improbable::database_sync::AssociatePathWithClientResponse& Value)
{
	uint32 Result = 1327;
	
	return Result;
}

} // namespace database_sync
} // namespace improbable
