// Generated by Unreal External Schema Codegen

#include "BatchOperationResponse.h"
#include <set>
#include "../../MapEquals.h"

// Generated from C:\DEV\UnrealGDKExampleProject\Game\Plugins\UnrealGDK\SpatialGDK\Build\Scripts\dbsync\database_sync.schema(253,1)
namespace improbable {
namespace database_sync {

BatchOperationResponse::BatchOperationResponse(
	const TArray<::improbable::database_sync::CompositeResponse>& Actions)
: _Actions{ Actions } {}

BatchOperationResponse::BatchOperationResponse() {}

bool BatchOperationResponse::operator==(const BatchOperationResponse& Value) const
{
	return _Actions == Value._Actions;
}

bool BatchOperationResponse::operator!=(const BatchOperationResponse& Value) const
{
	return !operator== (Value);
}

const TArray<::improbable::database_sync::CompositeResponse>& BatchOperationResponse::GetActions() const
{
	return _Actions;
}

TArray<::improbable::database_sync::CompositeResponse>& BatchOperationResponse::GetActions()
{
	return _Actions; 
}

BatchOperationResponse& BatchOperationResponse::SetActions(const TArray<::improbable::database_sync::CompositeResponse>& Value)
{
	_Actions = Value;
	return *this;
}

void BatchOperationResponse::Serialize(Schema_Object* SchemaObject) const
{
	// serializing field Actions = 1
	for (const ::improbable::database_sync::CompositeResponse& Element : _Actions)
	{
		Element.Serialize(Schema_AddObject(SchemaObject, 1));
	}
}

BatchOperationResponse BatchOperationResponse::Deserialize(Schema_Object* SchemaObject)
{
	BatchOperationResponse Data;
	
	// deserializing field Actions = 1
	{
		auto ListLength = Schema_GetObjectCount(SchemaObject, 1);
		TArray<::improbable::database_sync::CompositeResponse> ActionsList;
		ActionsList.SetNum(ListLength);
		for (uint32 i = 0; i < ListLength; ++i)
		{
			ActionsList[i] = ::improbable::database_sync::CompositeResponse::Deserialize(Schema_IndexObject(SchemaObject, 1, i));
		}
		Data._Actions = ActionsList;
	}
	
	return Data;
}

uint32 GetTypeHash(const improbable::database_sync::BatchOperationResponse& Value)
{
	uint32 Result = 1327;
	for (const auto& item : Value.GetActions())
	{
		Result = (Result * 977) + improbable::database_sync::GetTypeHash(item);
	}
	return Result;
}

} // namespace database_sync
} // namespace improbable
