// Generated by Unreal External Schema Codegen

#pragma once

#include "CoreMinimal.h"
#include "Utils/SchemaOption.h"
#include <WorkerSDK/improbable/c_schema.h>
#include <WorkerSDK/improbable/c_worker.h>

#include "../../ExternalSchemaHelperFunctions.h"

#include "../../improbable/database_sync/CompositeRequest.h"

namespace improbable {
namespace database_sync {

// Generated from C:\DEV\UnrealGDKExampleProject\Game\Plugins\UnrealGDK\SpatialGDK\Build\Scripts\dbsync\database_sync.schema(248,1)
class BatchOperationRequest : public improbable::SpatialType
{
public:
	// Creates a new instance with specified arguments for each field.
	BatchOperationRequest(const TArray<::improbable::database_sync::CompositeRequest>& Actions);
	// Creates a new instance with default values for each field.
	BatchOperationRequest();
	// Creates a new instance with default values for each field. This is
	// equivalent to a default-constructed instance.
	static BatchOperationRequest Create() { return {}; }
	// Copyable and movable.
	BatchOperationRequest(BatchOperationRequest&&) = default;
	BatchOperationRequest(const BatchOperationRequest&) = default;
	BatchOperationRequest& operator=(BatchOperationRequest&&) = default;
	BatchOperationRequest& operator=(const BatchOperationRequest&) = default;
	~BatchOperationRequest() = default;
	
	bool operator==(const BatchOperationRequest&) const;
	bool operator!=(const BatchOperationRequest&) const;
	
	// Serialize this object data into the C API argument
	void Serialize(Schema_Object* SchemaObject) const override;
	
	// Deserialize the C API object argument into an instance of this class and return it
	static BatchOperationRequest Deserialize(Schema_Object* SchemaObject);
	
	// Field Actions = 1
	const TArray<::improbable::database_sync::CompositeRequest>& GetActions() const;
	TArray<::improbable::database_sync::CompositeRequest>& GetActions();
	BatchOperationRequest& SetActions(const TArray<::improbable::database_sync::CompositeRequest>&);
	
private:
	TArray<::improbable::database_sync::CompositeRequest> _Actions;
};

inline uint32 GetTypeHash(const BatchOperationRequest& Value);

} // namespace database_sync
} // namespace improbable

