// Generated by Unreal External Schema Codegen

#pragma once

#include "CoreMinimal.h"
#include "Utils/SchemaOption.h"
#include <WorkerSDK/improbable/c_schema.h>
#include <WorkerSDK/improbable/c_worker.h>

#include "../../ExternalSchemaHelperFunctions.h"

#include "../../improbable/database_sync/IncrementRequest.h"
#include "../../improbable/database_sync/DecrementRequest.h"
#include "../../improbable/database_sync/SetParentRequest.h"
#include "../../improbable/database_sync/CreateRequest.h"
#include "../../improbable/database_sync/DeleteRequest.h"
#include "../../improbable/database_sync/GetItemRequest.h"
#include "../../improbable/database_sync/GetItemsRequest.h"

namespace improbable {
namespace database_sync {

// Generated from C:\DEV\UnrealGDKExampleProject\Game\Plugins\UnrealGDK\SpatialGDK\Build\Scripts\dbsync\database_sync.schema(227,1)
class CompositeRequest : public improbable::SpatialType
{
public:
	// Creates a new instance with specified arguments for each field.
	CompositeRequest(const SpatialGDK::TSchemaOption<::improbable::database_sync::IncrementRequest>& Increment, const SpatialGDK::TSchemaOption<::improbable::database_sync::DecrementRequest>& Decrement, const SpatialGDK::TSchemaOption<::improbable::database_sync::SetParentRequest>& SetParent, const SpatialGDK::TSchemaOption<::improbable::database_sync::CreateRequest>& Create, const SpatialGDK::TSchemaOption<::improbable::database_sync::DeleteRequest>& Delete, const SpatialGDK::TSchemaOption<::improbable::database_sync::GetItemRequest>& GetItem, const SpatialGDK::TSchemaOption<::improbable::database_sync::GetItemsRequest>& GetItems);
	// Creates a new instance with default values for each field.
	CompositeRequest();
	// Creates a new instance with default values for each field. This is
	// equivalent to a default-constructed instance.
	static CompositeRequest Create() { return {}; }
	// Copyable and movable.
	CompositeRequest(CompositeRequest&&) = default;
	CompositeRequest(const CompositeRequest&) = default;
	CompositeRequest& operator=(CompositeRequest&&) = default;
	CompositeRequest& operator=(const CompositeRequest&) = default;
	~CompositeRequest() = default;
	
	bool operator==(const CompositeRequest&) const;
	bool operator!=(const CompositeRequest&) const;
	
	// Serialize this object data into the C API argument
	void Serialize(Schema_Object* SchemaObject) const override;
	
	// Deserialize the C API object argument into an instance of this class and return it
	static CompositeRequest Deserialize(Schema_Object* SchemaObject);
	
	// Field Increment = 1
	const SpatialGDK::TSchemaOption<::improbable::database_sync::IncrementRequest>& GetIncrement() const;
	SpatialGDK::TSchemaOption<::improbable::database_sync::IncrementRequest>& GetIncrement();
	CompositeRequest& SetIncrement(const SpatialGDK::TSchemaOption<::improbable::database_sync::IncrementRequest>&);
	
	// Field Decrement = 2
	const SpatialGDK::TSchemaOption<::improbable::database_sync::DecrementRequest>& GetDecrement() const;
	SpatialGDK::TSchemaOption<::improbable::database_sync::DecrementRequest>& GetDecrement();
	CompositeRequest& SetDecrement(const SpatialGDK::TSchemaOption<::improbable::database_sync::DecrementRequest>&);
	
	// Field SetParent = 3
	const SpatialGDK::TSchemaOption<::improbable::database_sync::SetParentRequest>& GetSetParent() const;
	SpatialGDK::TSchemaOption<::improbable::database_sync::SetParentRequest>& GetSetParent();
	CompositeRequest& SetSetParent(const SpatialGDK::TSchemaOption<::improbable::database_sync::SetParentRequest>&);
	
	// Field Create = 4
	const SpatialGDK::TSchemaOption<::improbable::database_sync::CreateRequest>& GetCreate() const;
	SpatialGDK::TSchemaOption<::improbable::database_sync::CreateRequest>& GetCreate();
	CompositeRequest& SetCreate(const SpatialGDK::TSchemaOption<::improbable::database_sync::CreateRequest>&);
	
	// Field Delete = 5
	const SpatialGDK::TSchemaOption<::improbable::database_sync::DeleteRequest>& GetDelete() const;
	SpatialGDK::TSchemaOption<::improbable::database_sync::DeleteRequest>& GetDelete();
	CompositeRequest& SetDelete(const SpatialGDK::TSchemaOption<::improbable::database_sync::DeleteRequest>&);
	
	// Field GetItem = 6
	const SpatialGDK::TSchemaOption<::improbable::database_sync::GetItemRequest>& GetGetItem() const;
	SpatialGDK::TSchemaOption<::improbable::database_sync::GetItemRequest>& GetGetItem();
	CompositeRequest& SetGetItem(const SpatialGDK::TSchemaOption<::improbable::database_sync::GetItemRequest>&);
	
	// Field GetItems = 7
	const SpatialGDK::TSchemaOption<::improbable::database_sync::GetItemsRequest>& GetGetItems() const;
	SpatialGDK::TSchemaOption<::improbable::database_sync::GetItemsRequest>& GetGetItems();
	CompositeRequest& SetGetItems(const SpatialGDK::TSchemaOption<::improbable::database_sync::GetItemsRequest>&);
	
private:
	SpatialGDK::TSchemaOption<::improbable::database_sync::IncrementRequest> _Increment;
	SpatialGDK::TSchemaOption<::improbable::database_sync::DecrementRequest> _Decrement;
	SpatialGDK::TSchemaOption<::improbable::database_sync::SetParentRequest> _SetParent;
	SpatialGDK::TSchemaOption<::improbable::database_sync::CreateRequest> _Create;
	SpatialGDK::TSchemaOption<::improbable::database_sync::DeleteRequest> _Delete;
	SpatialGDK::TSchemaOption<::improbable::database_sync::GetItemRequest> _GetItem;
	SpatialGDK::TSchemaOption<::improbable::database_sync::GetItemsRequest> _GetItems;
};

inline uint32 GetTypeHash(const CompositeRequest& Value);

} // namespace database_sync
} // namespace improbable

