// Generated by Unreal External Schema Codegen

#include "CreateRequest.h"
#include <set>
#include "../../MapEquals.h"

// Generated from C:\DEV\UnrealGDKExampleProject\Game\Plugins\UnrealGDK\SpatialGDK\Build\Scripts\dbsync\database_sync.schema(184,1)
namespace improbable {
namespace database_sync {

CreateRequest::CreateRequest(
	const ::improbable::database_sync::DatabaseSyncItem& Item, 
	const FString& WorkerId)
: _Item{ Item }
, _WorkerId{ WorkerId } {}

CreateRequest::CreateRequest() {}

bool CreateRequest::operator==(const CreateRequest& Value) const
{
	return _Item == Value._Item && 
	_WorkerId == Value._WorkerId;
}

bool CreateRequest::operator!=(const CreateRequest& Value) const
{
	return !operator== (Value);
}

const ::improbable::database_sync::DatabaseSyncItem& CreateRequest::GetItem() const
{
	return _Item;
}

::improbable::database_sync::DatabaseSyncItem& CreateRequest::GetItem()
{
	return _Item; 
}

CreateRequest& CreateRequest::SetItem(const ::improbable::database_sync::DatabaseSyncItem& Value)
{
	_Item = Value;
	return *this;
}

const FString& CreateRequest::GetWorkerId() const
{
	return _WorkerId;
}

FString& CreateRequest::GetWorkerId()
{
	return _WorkerId; 
}

CreateRequest& CreateRequest::SetWorkerId(const FString& Value)
{
	_WorkerId = Value;
	return *this;
}

void CreateRequest::Serialize(Schema_Object* SchemaObject) const
{
	// serializing field Item = 1
	_Item.Serialize(Schema_AddObject(SchemaObject, 1));
	// serializing field WorkerId = 2
	::improbable::utils::AddString(SchemaObject, 2, _WorkerId);
}

CreateRequest CreateRequest::Deserialize(Schema_Object* SchemaObject)
{
	CreateRequest Data;
	
	// deserializing field Item = 1
	Data._Item = ::improbable::database_sync::DatabaseSyncItem::Deserialize(Schema_GetObject(SchemaObject, 1));
	
	// deserializing field WorkerId = 2
	Data._WorkerId = ::improbable::utils::GetString(SchemaObject, 2);
	
	return Data;
}

uint32 GetTypeHash(const improbable::database_sync::CreateRequest& Value)
{
	uint32 Result = 1327;
	Result = (Result * 977) + improbable::database_sync::GetTypeHash(Value.GetItem());
	Result = (Result * 977) + ::GetTypeHash(Value.GetWorkerId());
	return Result;
}

} // namespace database_sync
} // namespace improbable
