// Generated by Unreal External Schema Codegen

#include "CreateResponse.h"
#include <set>
#include "../../MapEquals.h"

// Generated from C:\DEV\UnrealGDKExampleProject\Game\Plugins\UnrealGDK\SpatialGDK\Build\Scripts\dbsync\database_sync.schema(194,1)
namespace improbable {
namespace database_sync {

CreateResponse::CreateResponse() {}

bool CreateResponse::operator==(const CreateResponse& Value) const
{
	return true;
}

bool CreateResponse::operator!=(const CreateResponse& Value) const
{
	return !operator== (Value);
}

void CreateResponse::Serialize(Schema_Object* SchemaObject) const {}

CreateResponse CreateResponse::Deserialize(Schema_Object* SchemaObject)
{
	return CreateResponse::Create();
}

uint32 GetTypeHash(const improbable::database_sync::CreateResponse& Value)
{
	uint32 Result = 1327;
	
	return Result;
}

} // namespace database_sync
} // namespace improbable
