// Generated by Unreal External Schema Codegen

#pragma once

#include "CoreMinimal.h"
#include "Utils/SchemaOption.h"
#include <WorkerSDK/improbable/c_schema.h>
#include <WorkerSDK/improbable/c_worker.h>

#include "../../ExternalSchemaHelperFunctions.h"

#include "../../improbable/database_sync/DatabaseSyncItem.h"

namespace improbable {
namespace database_sync {

// Generated from C:\DEV\UnrealGDKExampleProject\Game\Plugins\UnrealGDK\SpatialGDK\Build\Scripts\dbsync\database_sync.schema(184,1)
class CreateRequest : public improbable::SpatialType
{
public:
	// Creates a new instance with specified arguments for each field.
	CreateRequest(const ::improbable::database_sync::DatabaseSyncItem& Item, const FString& WorkerId);
	// Creates a new instance with default values for each field.
	CreateRequest();
	// Creates a new instance with default values for each field. This is
	// equivalent to a default-constructed instance.
	static CreateRequest Create() { return {}; }
	// Copyable and movable.
	CreateRequest(CreateRequest&&) = default;
	CreateRequest(const CreateRequest&) = default;
	CreateRequest& operator=(CreateRequest&&) = default;
	CreateRequest& operator=(const CreateRequest&) = default;
	~CreateRequest() = default;
	
	bool operator==(const CreateRequest&) const;
	bool operator!=(const CreateRequest&) const;
	
	// Serialize this object data into the C API argument
	void Serialize(Schema_Object* SchemaObject) const override;
	
	// Deserialize the C API object argument into an instance of this class and return it
	static CreateRequest Deserialize(Schema_Object* SchemaObject);
	
	// Field Item = 1
	const ::improbable::database_sync::DatabaseSyncItem& GetItem() const;
	::improbable::database_sync::DatabaseSyncItem& GetItem();
	CreateRequest& SetItem(const ::improbable::database_sync::DatabaseSyncItem&);
	
	// Field WorkerId = 2
	const FString& GetWorkerId() const;
	FString& GetWorkerId();
	CreateRequest& SetWorkerId(const FString&);
	
private:
	::improbable::database_sync::DatabaseSyncItem _Item;
	FString _WorkerId;
};

inline uint32 GetTypeHash(const CreateRequest& Value);

} // namespace database_sync
} // namespace improbable

