// Generated by Unreal External Schema Codegen

#pragma once

#include "CoreMinimal.h"
#include "Utils/SchemaOption.h"
#include <WorkerSDK/improbable/c_schema.h>
#include <WorkerSDK/improbable/c_worker.h>

#include "../../ExternalSchemaHelperFunctions.h"

namespace improbable {
namespace database_sync {

// Generated from C:\DEV\UnrealGDKExampleProject\Game\Plugins\UnrealGDK\SpatialGDK\Build\Scripts\dbsync\database_sync.schema(136,1)
class DecrementRequest : public improbable::SpatialType
{
public:
	// Creates a new instance with specified arguments for each field.
	DecrementRequest(const FString& Path, int64 Amount, const FString& WorkerId);
	// Creates a new instance with default values for each field.
	DecrementRequest();
	// Creates a new instance with default values for each field. This is
	// equivalent to a default-constructed instance.
	static DecrementRequest Create() { return {}; }
	// Copyable and movable.
	DecrementRequest(DecrementRequest&&) = default;
	DecrementRequest(const DecrementRequest&) = default;
	DecrementRequest& operator=(DecrementRequest&&) = default;
	DecrementRequest& operator=(const DecrementRequest&) = default;
	~DecrementRequest() = default;
	
	bool operator==(const DecrementRequest&) const;
	bool operator!=(const DecrementRequest&) const;
	
	// Serialize this object data into the C API argument
	void Serialize(Schema_Object* SchemaObject) const override;
	
	// Deserialize the C API object argument into an instance of this class and return it
	static DecrementRequest Deserialize(Schema_Object* SchemaObject);
	
	// Field Path = 1
	const FString& GetPath() const;
	FString& GetPath();
	DecrementRequest& SetPath(const FString&);
	
	// Field Amount = 2
	int64 GetAmount() const;
	int64& GetAmount();
	DecrementRequest& SetAmount(int64);
	
	// Field WorkerId = 3
	const FString& GetWorkerId() const;
	FString& GetWorkerId();
	DecrementRequest& SetWorkerId(const FString&);
	
private:
	FString _Path;
	int64 _Amount;
	FString _WorkerId;
};

inline uint32 GetTypeHash(const DecrementRequest& Value);

} // namespace database_sync
} // namespace improbable

