// Generated by Unreal External Schema Codegen

#pragma once

#include "CoreMinimal.h"
#include "Utils/SchemaOption.h"
#include <WorkerSDK/improbable/c_schema.h>
#include <WorkerSDK/improbable/c_worker.h>

#include "../../ExternalSchemaHelperFunctions.h"

namespace improbable {
namespace database_sync {

// Generated from C:\DEV\UnrealGDKExampleProject\Game\Plugins\UnrealGDK\SpatialGDK\Build\Scripts\dbsync\database_sync.schema(151,1)
class DecrementResponse : public improbable::SpatialType
{
public:
	// Creates a new instance with specified arguments for each field.
	DecrementResponse(int64 NewCount);
	// Creates a new instance with default values for each field.
	DecrementResponse();
	// Creates a new instance with default values for each field. This is
	// equivalent to a default-constructed instance.
	static DecrementResponse Create() { return {}; }
	// Copyable and movable.
	DecrementResponse(DecrementResponse&&) = default;
	DecrementResponse(const DecrementResponse&) = default;
	DecrementResponse& operator=(DecrementResponse&&) = default;
	DecrementResponse& operator=(const DecrementResponse&) = default;
	~DecrementResponse() = default;
	
	bool operator==(const DecrementResponse&) const;
	bool operator!=(const DecrementResponse&) const;
	
	// Serialize this object data into the C API argument
	void Serialize(Schema_Object* SchemaObject) const override;
	
	// Deserialize the C API object argument into an instance of this class and return it
	static DecrementResponse Deserialize(Schema_Object* SchemaObject);
	
	// Field NewCount = 1
	int64 GetNewCount() const;
	int64& GetNewCount();
	DecrementResponse& SetNewCount(int64);
	
private:
	int64 _NewCount;
};

inline uint32 GetTypeHash(const DecrementResponse& Value);

} // namespace database_sync
} // namespace improbable

