// Generated by Unreal External Schema Codegen

#pragma once

#include "CoreMinimal.h"
#include "Utils/SchemaOption.h"
#include <WorkerSDK/improbable/c_schema.h>
#include <WorkerSDK/improbable/c_worker.h>

#include "../../ExternalSchemaHelperFunctions.h"

namespace improbable {
namespace database_sync {

// Generated from C:\DEV\UnrealGDKExampleProject\Game\Plugins\UnrealGDK\SpatialGDK\Build\Scripts\dbsync\database_sync.schema(206,1)
class DeleteResponse : public improbable::SpatialType
{
public:
	// Creates a new instance with specified arguments for each field.
	DeleteResponse(int64 ItemCount);
	// Creates a new instance with default values for each field.
	DeleteResponse();
	// Creates a new instance with default values for each field. This is
	// equivalent to a default-constructed instance.
	static DeleteResponse Create() { return {}; }
	// Copyable and movable.
	DeleteResponse(DeleteResponse&&) = default;
	DeleteResponse(const DeleteResponse&) = default;
	DeleteResponse& operator=(DeleteResponse&&) = default;
	DeleteResponse& operator=(const DeleteResponse&) = default;
	~DeleteResponse() = default;
	
	bool operator==(const DeleteResponse&) const;
	bool operator!=(const DeleteResponse&) const;
	
	// Serialize this object data into the C API argument
	void Serialize(Schema_Object* SchemaObject) const override;
	
	// Deserialize the C API object argument into an instance of this class and return it
	static DeleteResponse Deserialize(Schema_Object* SchemaObject);
	
	// Field ItemCount = 1
	int64 GetItemCount() const;
	int64& GetItemCount();
	DeleteResponse& SetItemCount(int64);
	
private:
	int64 _ItemCount;
};

inline uint32 GetTypeHash(const DeleteResponse& Value);

} // namespace database_sync
} // namespace improbable

