// Generated by Unreal External Schema Codegen

#include "DeleteResponse.h"
#include <set>
#include "../../MapEquals.h"

// Generated from C:\DEV\UnrealGDKExampleProject\Game\Plugins\UnrealGDK\SpatialGDK\Build\Scripts\dbsync\database_sync.schema(206,1)
namespace improbable {
namespace database_sync {

DeleteResponse::DeleteResponse(
	int64 ItemCount)
: _ItemCount{ ItemCount } {}

DeleteResponse::DeleteResponse() {}

bool DeleteResponse::operator==(const DeleteResponse& Value) const
{
	return _ItemCount == Value._ItemCount;
}

bool DeleteResponse::operator!=(const DeleteResponse& Value) const
{
	return !operator== (Value);
}

int64 DeleteResponse::GetItemCount() const
{
	return _ItemCount;
}

int64& DeleteResponse::GetItemCount()
{
	return _ItemCount; 
}

DeleteResponse& DeleteResponse::SetItemCount(int64 Value)
{
	_ItemCount = Value;
	return *this;
}

void DeleteResponse::Serialize(Schema_Object* SchemaObject) const
{
	// serializing field ItemCount = 1
	Schema_AddInt64(SchemaObject, 1, _ItemCount);
}

DeleteResponse DeleteResponse::Deserialize(Schema_Object* SchemaObject)
{
	DeleteResponse Data;
	
	// deserializing field ItemCount = 1
	Data._ItemCount = Schema_GetInt64(SchemaObject, 1);
	
	return Data;
}

uint32 GetTypeHash(const improbable::database_sync::DeleteResponse& Value)
{
	uint32 Result = 1327;
	Result = (Result * 977) + ::GetTypeHash(Value.GetItemCount());
	return Result;
}

} // namespace database_sync
} // namespace improbable
