// Generated by Unreal External Schema Codegen

#pragma once

#include "CoreMinimal.h"
#include "Utils/SchemaOption.h"
#include <WorkerSDK/improbable/c_schema.h>
#include <WorkerSDK/improbable/c_worker.h>

#include "../../ExternalSchemaHelperFunctions.h"

namespace improbable {
namespace database_sync {

// Generated from C:\DEV\UnrealGDKExampleProject\Game\Plugins\UnrealGDK\SpatialGDK\Build\Scripts\dbsync\database_sync.schema(77,1)
class GetItemRequest : public improbable::SpatialType
{
public:
	// Creates a new instance with specified arguments for each field.
	GetItemRequest(const FString& Path, const FString& WorkerId);
	// Creates a new instance with default values for each field.
	GetItemRequest();
	// Creates a new instance with default values for each field. This is
	// equivalent to a default-constructed instance.
	static GetItemRequest Create() { return {}; }
	// Copyable and movable.
	GetItemRequest(GetItemRequest&&) = default;
	GetItemRequest(const GetItemRequest&) = default;
	GetItemRequest& operator=(GetItemRequest&&) = default;
	GetItemRequest& operator=(const GetItemRequest&) = default;
	~GetItemRequest() = default;
	
	bool operator==(const GetItemRequest&) const;
	bool operator!=(const GetItemRequest&) const;
	
	// Serialize this object data into the C API argument
	void Serialize(Schema_Object* SchemaObject) const override;
	
	// Deserialize the C API object argument into an instance of this class and return it
	static GetItemRequest Deserialize(Schema_Object* SchemaObject);
	
	// Field Path = 1
	const FString& GetPath() const;
	FString& GetPath();
	GetItemRequest& SetPath(const FString&);
	
	// Field WorkerId = 2
	const FString& GetWorkerId() const;
	FString& GetWorkerId();
	GetItemRequest& SetWorkerId(const FString&);
	
private:
	FString _Path;
	FString _WorkerId;
};

inline uint32 GetTypeHash(const GetItemRequest& Value);

} // namespace database_sync
} // namespace improbable

