// Generated by Unreal External Schema Codegen

#pragma once

#include "CoreMinimal.h"
#include "Utils/SchemaOption.h"
#include <WorkerSDK/improbable/c_schema.h>
#include <WorkerSDK/improbable/c_worker.h>

#include "../../ExternalSchemaHelperFunctions.h"

#include "../../improbable/database_sync/GetItemDepth.h"

namespace improbable {
namespace database_sync {

// Generated from C:\DEV\UnrealGDKExampleProject\Game\Plugins\UnrealGDK\SpatialGDK\Build\Scripts\dbsync\database_sync.schema(99,1)
class GetItemsRequest : public improbable::SpatialType
{
public:
	// Creates a new instance with specified arguments for each field.
	GetItemsRequest(const FString& Path, const ::improbable::database_sync::GetItemDepth& Depth, const FString& WorkerId);
	// Creates a new instance with default values for each field.
	GetItemsRequest();
	// Creates a new instance with default values for each field. This is
	// equivalent to a default-constructed instance.
	static GetItemsRequest Create() { return {}; }
	// Copyable and movable.
	GetItemsRequest(GetItemsRequest&&) = default;
	GetItemsRequest(const GetItemsRequest&) = default;
	GetItemsRequest& operator=(GetItemsRequest&&) = default;
	GetItemsRequest& operator=(const GetItemsRequest&) = default;
	~GetItemsRequest() = default;
	
	bool operator==(const GetItemsRequest&) const;
	bool operator!=(const GetItemsRequest&) const;
	
	// Serialize this object data into the C API argument
	void Serialize(Schema_Object* SchemaObject) const override;
	
	// Deserialize the C API object argument into an instance of this class and return it
	static GetItemsRequest Deserialize(Schema_Object* SchemaObject);
	
	// Field Path = 1
	const FString& GetPath() const;
	FString& GetPath();
	GetItemsRequest& SetPath(const FString&);
	
	// Field Depth = 2
	const ::improbable::database_sync::GetItemDepth& GetDepth() const;
	::improbable::database_sync::GetItemDepth& GetDepth();
	GetItemsRequest& SetDepth(const ::improbable::database_sync::GetItemDepth&);
	
	// Field WorkerId = 3
	const FString& GetWorkerId() const;
	FString& GetWorkerId();
	GetItemsRequest& SetWorkerId(const FString&);
	
private:
	FString _Path;
	::improbable::database_sync::GetItemDepth _Depth;
	FString _WorkerId;
};

inline uint32 GetTypeHash(const GetItemsRequest& Value);

} // namespace database_sync
} // namespace improbable

