// Generated by Unreal External Schema Codegen

#include "GetItemResponse.h"
#include <set>
#include "../../MapEquals.h"

// Generated from C:\DEV\UnrealGDKExampleProject\Game\Plugins\UnrealGDK\SpatialGDK\Build\Scripts\dbsync\database_sync.schema(87,1)
namespace improbable {
namespace database_sync {

GetItemResponse::GetItemResponse(
	const ::improbable::database_sync::DatabaseSyncItem& Item)
: _Item{ Item } {}

GetItemResponse::GetItemResponse() {}

bool GetItemResponse::operator==(const GetItemResponse& Value) const
{
	return _Item == Value._Item;
}

bool GetItemResponse::operator!=(const GetItemResponse& Value) const
{
	return !operator== (Value);
}

const ::improbable::database_sync::DatabaseSyncItem& GetItemResponse::GetItem() const
{
	return _Item;
}

::improbable::database_sync::DatabaseSyncItem& GetItemResponse::GetItem()
{
	return _Item; 
}

GetItemResponse& GetItemResponse::SetItem(const ::improbable::database_sync::DatabaseSyncItem& Value)
{
	_Item = Value;
	return *this;
}

void GetItemResponse::Serialize(Schema_Object* SchemaObject) const
{
	// serializing field Item = 1
	_Item.Serialize(Schema_AddObject(SchemaObject, 1));
}

GetItemResponse GetItemResponse::Deserialize(Schema_Object* SchemaObject)
{
	GetItemResponse Data;
	
	// deserializing field Item = 1
	Data._Item = ::improbable::database_sync::DatabaseSyncItem::Deserialize(Schema_GetObject(SchemaObject, 1));
	
	return Data;
}

uint32 GetTypeHash(const improbable::database_sync::GetItemResponse& Value)
{
	uint32 Result = 1327;
	Result = (Result * 977) + improbable::database_sync::GetTypeHash(Value.GetItem());
	return Result;
}

} // namespace database_sync
} // namespace improbable
