// Generated by Unreal External Schema Codegen

#pragma once

#include <cstdint>
#include <functional>

namespace improbable {
namespace database_sync {

// Generated from dbsync/database_sync.schema(91,1)
enum class GetItemDepth : uint32
{
	RECURSIVE = 0,
	CHILDREN_ONLY = 1,
};

} // namespace database_sync
} // namespace improbable
