// Generated by Unreal External Schema Codegen

#pragma once

#include "CoreMinimal.h"
#include "Utils/SchemaOption.h"
#include <WorkerSDK/improbable/c_schema.h>
#include <WorkerSDK/improbable/c_worker.h>

#include "../../ExternalSchemaHelperFunctions.h"

namespace improbable {
namespace database_sync {

// Generated from C:\DEV\UnrealGDKExampleProject\Game\Plugins\UnrealGDK\SpatialGDK\Build\Scripts\dbsync\database_sync.schema(211,1)
class GetMetricsRequest : public improbable::SpatialType
{
public:
	// Creates a new instance with default values for each field.
	GetMetricsRequest();
	// Creates a new instance with default values for each field. This is
	// equivalent to a default-constructed instance.
	static GetMetricsRequest Create() { return {}; }
	// Copyable and movable.
	GetMetricsRequest(GetMetricsRequest&&) = default;
	GetMetricsRequest(const GetMetricsRequest&) = default;
	GetMetricsRequest& operator=(GetMetricsRequest&&) = default;
	GetMetricsRequest& operator=(const GetMetricsRequest&) = default;
	~GetMetricsRequest() = default;
	
	bool operator==(const GetMetricsRequest&) const;
	bool operator!=(const GetMetricsRequest&) const;
	
	// Serialize this object data into the C API argument
	void Serialize(Schema_Object* SchemaObject) const override;
	
	// Deserialize the C API object argument into an instance of this class and return it
	static GetMetricsRequest Deserialize(Schema_Object* SchemaObject);
	
};

inline uint32 GetTypeHash(const GetMetricsRequest& Value);

} // namespace database_sync
} // namespace improbable

