// Generated by Unreal External Schema Codegen

#pragma once

#include "CoreMinimal.h"
#include "Utils/SchemaOption.h"
#include <WorkerSDK/improbable/c_schema.h>
#include <WorkerSDK/improbable/c_worker.h>

#include "../../ExternalSchemaHelperFunctions.h"

namespace improbable {
namespace database_sync {

// Generated from C:\DEV\UnrealGDKExampleProject\Game\Plugins\UnrealGDK\SpatialGDK\Build\Scripts\dbsync\database_sync.schema(131,1)
class IncrementResponse : public improbable::SpatialType
{
public:
	// Creates a new instance with specified arguments for each field.
	IncrementResponse(int64 NewCount);
	// Creates a new instance with default values for each field.
	IncrementResponse();
	// Creates a new instance with default values for each field. This is
	// equivalent to a default-constructed instance.
	static IncrementResponse Create() { return {}; }
	// Copyable and movable.
	IncrementResponse(IncrementResponse&&) = default;
	IncrementResponse(const IncrementResponse&) = default;
	IncrementResponse& operator=(IncrementResponse&&) = default;
	IncrementResponse& operator=(const IncrementResponse&) = default;
	~IncrementResponse() = default;
	
	bool operator==(const IncrementResponse&) const;
	bool operator!=(const IncrementResponse&) const;
	
	// Serialize this object data into the C API argument
	void Serialize(Schema_Object* SchemaObject) const override;
	
	// Deserialize the C API object argument into an instance of this class and return it
	static IncrementResponse Deserialize(Schema_Object* SchemaObject);
	
	// Field NewCount = 1
	int64 GetNewCount() const;
	int64& GetNewCount();
	IncrementResponse& SetNewCount(int64);
	
private:
	int64 _NewCount;
};

inline uint32 GetTypeHash(const IncrementResponse& Value);

} // namespace database_sync
} // namespace improbable

