// Generated by Unreal External Schema Codegen

#pragma once

#include "CoreMinimal.h"
#include "Utils/SchemaOption.h"
#include <WorkerSDK/improbable/c_schema.h>
#include <WorkerSDK/improbable/c_worker.h>

#include "../../ExternalSchemaHelperFunctions.h"

namespace improbable {
namespace database_sync {

// Generated from C:\DEV\UnrealGDKExampleProject\Game\Plugins\UnrealGDK\SpatialGDK\Build\Scripts\dbsync\database_sync.schema(10,1)
class ProfileIdAnnotation : public improbable::SpatialType
{
public:
	// Creates a new instance with default values for each field.
	ProfileIdAnnotation();
	// Creates a new instance with default values for each field. This is
	// equivalent to a default-constructed instance.
	static ProfileIdAnnotation Create() { return {}; }
	// Copyable and movable.
	ProfileIdAnnotation(ProfileIdAnnotation&&) = default;
	ProfileIdAnnotation(const ProfileIdAnnotation&) = default;
	ProfileIdAnnotation& operator=(ProfileIdAnnotation&&) = default;
	ProfileIdAnnotation& operator=(const ProfileIdAnnotation&) = default;
	~ProfileIdAnnotation() = default;
	
	bool operator==(const ProfileIdAnnotation&) const;
	bool operator!=(const ProfileIdAnnotation&) const;
	
	// Serialize this object data into the C API argument
	void Serialize(Schema_Object* SchemaObject) const override;
	
	// Deserialize the C API object argument into an instance of this class and return it
	static ProfileIdAnnotation Deserialize(Schema_Object* SchemaObject);
	
};

inline uint32 GetTypeHash(const ProfileIdAnnotation& Value);

} // namespace database_sync
} // namespace improbable

