// Generated by Unreal External Schema Codegen

#include "ProfileIdAnnotation.h"
#include <set>
#include "../../MapEquals.h"

// Generated from C:\DEV\UnrealGDKExampleProject\Game\Plugins\UnrealGDK\SpatialGDK\Build\Scripts\dbsync\database_sync.schema(10,1)
namespace improbable {
namespace database_sync {

ProfileIdAnnotation::ProfileIdAnnotation() {}

bool ProfileIdAnnotation::operator==(const ProfileIdAnnotation& Value) const
{
	return true;
}

bool ProfileIdAnnotation::operator!=(const ProfileIdAnnotation& Value) const
{
	return !operator== (Value);
}

void ProfileIdAnnotation::Serialize(Schema_Object* SchemaObject) const {}

ProfileIdAnnotation ProfileIdAnnotation::Deserialize(Schema_Object* SchemaObject)
{
	return ProfileIdAnnotation::Create();
}

uint32 GetTypeHash(const improbable::database_sync::ProfileIdAnnotation& Value)
{
	uint32 Result = 1327;
	
	return Result;
}

} // namespace database_sync
} // namespace improbable
