// Generated by Unreal External Schema Codegen

#pragma once

#include "CoreMinimal.h"
#include "Utils/SchemaOption.h"
#include <WorkerSDK/improbable/c_schema.h>
#include <WorkerSDK/improbable/c_worker.h>

#include "../../ExternalSchemaHelperFunctions.h"

namespace improbable {
namespace database_sync {

// Generated from C:\DEV\UnrealGDKExampleProject\Game\Plugins\UnrealGDK\SpatialGDK\Build\Scripts\dbsync\database_sync.schema(156,1)
class SetParentRequest : public improbable::SpatialType
{
public:
	// Creates a new instance with specified arguments for each field.
	SetParentRequest(const FString& Path, const FString& NewParent, const FString& WorkerId);
	// Creates a new instance with default values for each field.
	SetParentRequest();
	// Creates a new instance with default values for each field. This is
	// equivalent to a default-constructed instance.
	static SetParentRequest Create() { return {}; }
	// Copyable and movable.
	SetParentRequest(SetParentRequest&&) = default;
	SetParentRequest(const SetParentRequest&) = default;
	SetParentRequest& operator=(SetParentRequest&&) = default;
	SetParentRequest& operator=(const SetParentRequest&) = default;
	~SetParentRequest() = default;
	
	bool operator==(const SetParentRequest&) const;
	bool operator!=(const SetParentRequest&) const;
	
	// Serialize this object data into the C API argument
	void Serialize(Schema_Object* SchemaObject) const override;
	
	// Deserialize the C API object argument into an instance of this class and return it
	static SetParentRequest Deserialize(Schema_Object* SchemaObject);
	
	// Field Path = 1
	const FString& GetPath() const;
	FString& GetPath();
	SetParentRequest& SetPath(const FString&);
	
	// Field NewParent = 2
	const FString& GetNewParent() const;
	FString& GetNewParent();
	SetParentRequest& SetNewParent(const FString&);
	
	// Field WorkerId = 3
	const FString& GetWorkerId() const;
	FString& GetWorkerId();
	SetParentRequest& SetWorkerId(const FString&);
	
private:
	FString _Path;
	FString _NewParent;
	FString _WorkerId;
};

inline uint32 GetTypeHash(const SetParentRequest& Value);

} // namespace database_sync
} // namespace improbable

