// Generated by Unreal External Schema Codegen

#pragma once

#include "CoreMinimal.h"
#include "Utils/SchemaOption.h"
#include <WorkerSDK/improbable/c_schema.h>
#include <WorkerSDK/improbable/c_worker.h>

#include "../../ExternalSchemaHelperFunctions.h"

namespace improbable {
namespace database_sync {

// Generated from C:\DEV\UnrealGDKExampleProject\Game\Plugins\UnrealGDK\SpatialGDK\Build\Scripts\dbsync\database_sync.schema(14,1)
class ValueAnnotation : public improbable::SpatialType
{
public:
	// Creates a new instance with default values for each field.
	ValueAnnotation();
	// Creates a new instance with default values for each field. This is
	// equivalent to a default-constructed instance.
	static ValueAnnotation Create() { return {}; }
	// Copyable and movable.
	ValueAnnotation(ValueAnnotation&&) = default;
	ValueAnnotation(const ValueAnnotation&) = default;
	ValueAnnotation& operator=(ValueAnnotation&&) = default;
	ValueAnnotation& operator=(const ValueAnnotation&) = default;
	~ValueAnnotation() = default;
	
	bool operator==(const ValueAnnotation&) const;
	bool operator!=(const ValueAnnotation&) const;
	
	// Serialize this object data into the C API argument
	void Serialize(Schema_Object* SchemaObject) const override;
	
	// Deserialize the C API object argument into an instance of this class and return it
	static ValueAnnotation Deserialize(Schema_Object* SchemaObject);
	
};

inline uint32 GetTypeHash(const ValueAnnotation& Value);

} // namespace database_sync
} // namespace improbable

