// Generated by Unreal External Schema Codegen

#include "ValueListAnnotation.h"
#include <set>
#include "../../MapEquals.h"

// Generated from C:\DEV\UnrealGDKExampleProject\Game\Plugins\UnrealGDK\SpatialGDK\Build\Scripts\dbsync\database_sync.schema(19,1)
namespace improbable {
namespace database_sync {

ValueListAnnotation::ValueListAnnotation() {}

bool ValueListAnnotation::operator==(const ValueListAnnotation& Value) const
{
	return true;
}

bool ValueListAnnotation::operator!=(const ValueListAnnotation& Value) const
{
	return !operator== (Value);
}

void ValueListAnnotation::Serialize(Schema_Object* SchemaObject) const {}

ValueListAnnotation ValueListAnnotation::Deserialize(Schema_Object* SchemaObject)
{
	return ValueListAnnotation::Create();
}

uint32 GetTypeHash(const improbable::database_sync::ValueListAnnotation& Value)
{
	uint32 Result = 1327;
	
	return Result;
}

} // namespace database_sync
} // namespace improbable
